name: Build and Train Model

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: python main.py

      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl
